### PR TITLE
fix: provide api base url and login web url by env variables

### PR DESCRIPTION
**Pull request by enpitsuLin**
### Description

Follow has been officially launched for alpha testing today, so shall we change those dev URLs that need to be visited by Vercel authorized to its prod version?

### CODE REVIEW

**Comment by hyoban** [comment]
Can you please help me extract it as a common constant？Thanks！

**Comment by hyoban** [comment]
Use a Vite env like `VITE_API_URL`

**Comment by enpitsuLin** [comment]
make more sense to use dotenv, I'll take it later

**Comment by enpitsuLin** [comment]
Done, API base URL and login URL can be controlled by env variables, and it also provides a `.env.example` file for reference

**Comment by hyoban** [comment]
LGTM, thanks for your contribution!

**Pull request merged**
